# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2022-10-19 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nme', models.CharField(max_length=20)),
                ('add', models.CharField(max_length=50)),
                ('eml', models.EmailField(max_length=20)),
                ('usr', models.CharField(max_length=15)),
                ('psw', models.CharField(max_length=8)),
            ],
        ),
    ]
